# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db8c2a51106d6b4e940c280219decff33046112e1257b7756d222409017d7248703bb35651872d764ecf20036cfe728e23c2d7891f2ac8a7ab90d0383ad41b3

test:
  secret_key_base: 234967e63c86bbb6475c389c8d2e6110185d96a0f417d80796e5b575b649d11963675c5b32259eb3266109b304c85b5fa1996f8b190e4dfb62acb3b40a2fd23a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
